name: Site
description: 'Provides site components.'
type: module
core: 8.x
dependencies:
  - block_content
  - ckeditor
  - contact
  - editor
  - field
  - filter
  - rdf
  - site_settings_site
  - taxonomy
  - text
package: Config
